### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by chrissieh** [boesiii/flowtrace#3]
Flow Trace was working well but havent used it for a while and now no longer working....

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/xxxxx/.qgis2/python/plugins\flowTrace\flowtrace.py", line 117, in run
    upstream_coord = nodes[0]
IndexError: list index out of range

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.2-Wien Wien, 1b929ef

Python path: ['C:/Users/xxxxx/.qgis2/python/plugins\\processing', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python', u'C:/Users/xxxxx/.qgis2/python', u'C:/Users/xxxxx/.qgis2/python/plugins', 'C:/PROGRA~1/QGISWI~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\nose-1.3.3-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\certifi-14.05.14-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISWI~1\\bin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\pytz-2012j-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win-amd64.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\six-1.3.0-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlrd-0.9.2-py2.7.egg', 'C:\\PROGRA~1\\QGISWI~1\\apps\\Python27\\lib\\site-packages\\xlwt-0.7.5-py2.7.egg', u'C:/Users/xxxxx/.qgis2//python', 'C:\\Users\\xxxxx\\.qgis2\\python\\plugins\\DigitizingTools\\tools', 'C:\\PROGRA~1\\QGISWI~1\\apps\\qgis\\python\\plugins\\fTools\\tools', 'N:/GIS Projects/QGIS Templates']

**Comment by boesiii** [comment]
I just tested it using Qgis 2.12.3 and it worked fine.  What type of data are you working with?  Can you try with a different dataset?  Can you send me the dataset you are working on?

**Comment by chrissieh** [comment]
Hi boesiii

Thanks for the super quick response.
I have to apologise....  I was selecting the points along the polyline network layer instead of the line, hence flow trace could not work as expected.  I guess there is an opportunity here for a slight tweak to accommodate the need for an error handler in the case of a person (like myself!) selecting an invalid layer for flow trace to properly inform them of their mistake.

Cheers Chrissie

**Comment by boesiii** [comment]
Thanks.  I will add it.

**Comment by Juls3** [comment]
Hi boesiii, 

It turns out I have the same error:
```

IndexError: list index out of range 
Traceback (most recent call last):
  File "/Users/xxxx/.qgis2/python/plugins/flowTrace/flowtrace.py", line 117, in run
    upstream_coord = nodes[0]
IndexError: list index out of range


Python version : 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] 
QGIS version : 2.14.3-Essen Essen, exported 
```

Though I am selecting a MultiLineString layer, so I don't really get how to make this work ? 
My dataset consists in flow lines for the US from the NHD database. I've been told that to make Flowtrace work I'd need a starting point (which I have, on a different layer) and an elevation raster (which I also have on a different layer). But I can't make it work... Any ideas welcomed.

Thanks !

**Comment by boesiii** [comment]
Can you supply a sample dataset?

**Comment by boesiii** [comment]
Actually the only data you need to supply is a layer with polylines and a selected polyline from the same layer.  It does not work with points or rasters.

**Comment by boesiii** [comment]
Chris and Juls, I have added a new version.  Any chance you could download from github and test it out.  I added some error checking and modified some tolerance settings.

**Comment by chrissieh** [comment]
Hey boesiii
Downloaded from github and happy to report that when I selected the polylines, it worked as expected and if I selected a point, a nice eventhandler information window popped up to advise me I should be selecting line geometry only.  Beautiful work - well done :)  Thanks.
