### ISSUE TITLE
QGIS3 update

### ISSUE THREAD

**Issue by thbaumann** [boesiii/flowtrace#5]
Hi,
just a short question: Do you have plans to update flowtrace to be compatible with QGIS3?

regards,
Thomas

**Comment by boesiii** [comment]
Yes but haven't had much time to look at it.

**Comment by rdbath** [comment]
Thanks for the heads up (+)

**Comment by boesiii** [comment]
@rdbath I have just modified the code to Qgis3.  If you have a chance please see if it works on your end.  I have uploaded to Qgis Plugins also so when it is approved you should see it.

**Comment by rdbath** [comment]
thanks. I just downloaded the plugin from the official repo and tested it. What I recognised is that it does not work anymore with polyline layer. Is there a reason why you switched from
`nodes = feature.geometry().asMultiPolyline()`
to
`nodes = feature.geometry().asPolyline()`
?
The error is "LineString geometry cannot be converted to a multilinestring. Only multi linestring or curves are permitted."

**Comment by boesiii** [comment]
I kind of figured this would happen.  I mostly work with shapefiles and I think by default all shapefiles are multipolyline.  What type of files do you work with?  Any chance you can send my a sample and I can develop a fix.

**Comment by boesiii** [comment]
I have added a new version.  You can get it from the master version here or wait till it is published in the plugin repo.
