### ISSUE TITLE
Python error if I click "cancel" button

### ISSUE THREAD

**Issue by AlisterH** [boesiii/flowtrace#7]
In the QGIS 3 version the first dialog now has a cancel button, which is an improvement (It seems to me like there is no reason for the first dialog to exist without a cancel button, unless you intend to make it display the selected layer name or number of selected features or something).
But if I click the cancel button there is a python error:
````
2019-10-04T17:01:10     WARNING    Traceback (most recent call last):
              File "C:/Users/alistair/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\flowTrace\flowtrace.py", line 319, in run
              for fid in final_list:
             UnboundLocalError: local variable 'final_list' referenced before assignment

**Comment by boesiii** [comment]
I have added a fix.

**Comment by boesiii** [comment]
I just added a new version.  The current layer selection will now be displayed in the dialog box along with the number of currently selected features.  Thanks for the suggestion!
